apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Maharashtra1998@
        - name: MYSQL_DATABASE
          value: dineshdb
        - name: MYSQL_USER
          value: dinesh
        - name: MYSQL_PASSWORD
          value: Banglore#1998
        ports:
        - containerPort: 3306
          name: database
        
