apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: dineshmk/node-app:dinesh6                
        ports:
        - containerPort: 80
          name: web-app
        env:
        - name: DB_HOST
          value: db-server
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: dineshdb
        - name: DB_USER
          value: dinesh
        - name: DB_PASSWORD
          value: Banglore#1998
        
